#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { logger } from './logger.js';
import { statusTool } from './tools/status.js';
import { screenshotTool } from './tools/screenshot.js';
import { getUrlTool } from './tools/get-url.js';
import { navigateTool } from './tools/navigate.js';
import { clickTool } from './tools/click.js';
import { scrollTool } from './tools/scroll.js';
import { typeTool } from './tools/type.js';
import { getDomTool } from './tools/get-dom.js';
import { snapshotTool } from './tools/snapshot.js';
import { consoleLogsTool } from './tools/console-logs.js';
import { selectModeTool } from './tools/select-mode.js';
import { executeTool } from './tools/execute.js';
import { keyboardTool } from './tools/keyboard.js';
import { hoverTool } from './tools/hover.js';
import { selectOptionTool } from './tools/select-option.js';
import { waitForTool } from './tools/wait-for.js';
import { dialogTool } from './tools/dialog.js';
import { fileUploadTool } from './tools/file-upload.js';
import { dragDropTool } from './tools/drag-drop.js';
import { tabsTool } from './tools/tabs.js';
import { navigateBackTool } from './tools/navigate-back.js';
import { cookiesTool } from './tools/cookies.js';
import { storageTool } from './tools/storage.js';
import { extractTool } from './tools/extract.js';
import { pdfTool } from './tools/pdf.js';
import { networkTool } from './tools/network.js';
import { downloadsTool } from './tools/downloads.js';
import { statsTool } from './tools/stats.js';
import { macroTool } from './tools/macro.js';
import { authTool } from './tools/auth.js';
import { emulateTool } from './tools/emulate.js';
import { framesTool } from './tools/frames.js';
import { formFillTool } from './tools/form.js';
import { reloadTool } from './tools/reload.js';
import { navigateForwardTool } from './tools/navigate-forward.js';
import { pageErrorsTool } from './tools/page-errors.js';
import { clipboardTool } from './tools/clipboard.js';
import { getElementTool } from './tools/get-element.js';
import { findTool } from './tools/find.js';
import { profilesTool } from './tools/profiles.js';
import { destroyAll } from './puppeteer-manager.js';
import { registerTool } from './tool-registry.js';
import type { ITool } from './types.js';

const tools: ITool[] = [
  statusTool,
  selectModeTool,
  screenshotTool,
  getUrlTool,
  navigateTool,
  clickTool,
  scrollTool,
  typeTool,
  getDomTool,
  snapshotTool,
  consoleLogsTool,
  executeTool,
  keyboardTool,
  hoverTool,
  selectOptionTool,
  waitForTool,
  dialogTool,
  fileUploadTool,
  dragDropTool,
  tabsTool,
  navigateBackTool,
  cookiesTool,
  storageTool,
  extractTool,
  pdfTool,
  networkTool,
  downloadsTool,
  statsTool,
  macroTool,
  authTool,
  emulateTool,
  framesTool,
  formFillTool,
  reloadTool,
  navigateForwardTool,
  pageErrorsTool,
  clipboardTool,
  getElementTool,
  findTool,
  profilesTool
];

async function shutdown(): Promise<void> {
  logger.info('Shutting down browser-control MCP server...');
  await destroyAll();
  process.exit(0);
}

async function main(): Promise<void> {
  process.on('SIGTERM', () => { void shutdown(); });
  process.on('SIGINT', () => { void shutdown(); });

  const server = new McpServer(
    { name: 'browser-control', version: '1.5.0' },
    {
      capabilities: { logging: {} },
      instructions: [
        'You have FULL BROWSER CONTROL through this MCP server. You CAN and SHOULD open browsers, navigate to any website, interact with web pages, and see what is on screen. You are NOT limited to fetching data — you have a real browser that renders pages, runs JavaScript, and lets you interact just like a human user.',
        '',
        '=== CAPABILITIES ===',
        'You can do ALL of the following:',
        '- Open a browser (headless background browser OR connect to the user\'s real Chrome via debug port)',
        '- Navigate to ANY URL: public websites, localhost, web apps, admin panels, any page',
        '- Take screenshots and visually analyze what you see (layout, design, content, errors)',
        '- Click ANY element: buttons, links, menus, dropdowns, tabs, checkboxes, radio buttons',
        '- Fill out forms: type into text inputs, search bars, textareas, login fields, any input',
        '- Submit forms: fill fields then click submit/send/login buttons',
        '- Scroll pages: up, down, left, right by any pixel amount',
        '- Read the full HTML/DOM source of any page for structural analysis',
        '- Check JavaScript console logs, errors, warnings for debugging',
        '- Open pages at any viewport size (desktop, tablet, mobile) with custom width/height',
        '- Maintain browser sessions: navigate multiple pages, stay logged in, keep cookies',
        '- Run multi-step flows: login → navigate → fill form → submit → verify result',
        '',
        '=== TWO BROWSER MODES ===',
        '1. HEADLESS MODE (mode="headless"): Opens an invisible background browser (Puppeteer).',
        '   - Best for: automated tasks, testing, checking websites, form submission, screenshots',
        '   - Supports custom viewport sizes via width/height params on browser_navigate',
        '   - Default viewport: 1024x768 pixels',
        '   - Has anti-bot detection bypass (spoofed user agent, no webdriver flag)',
        '   - Sessions persist: the sessionId returned lets you reuse the same browser across calls',
        '',
        '2. CONNECT MODE (mode="connect"): Connects to the user\'s real Chrome browser via CDP.',
        '   - Best for: seeing what the user sees, debugging their actual browser tab',
        '   - Requires Chrome to be running with --remote-debugging-port=9222',
        '   - If Chrome is not running with debug port, connect mode will auto-launch it for you',
        '   - Works on whatever tab the user has open',
        '',
        '=== HOW TO USE — STEP BY STEP ===',
        'Step 1: Call browser_select_mode to check what modes are available and set a default.',
        '  - Connect mode connects to real Chrome via CDP debug port',
        '  - If Chrome is available with debug port: ask user which mode they prefer',
        '  - If Chrome is NOT available: headless is auto-selected',
        'Step 2: Call browser_navigate with a URL to open the page.',
        '  - Pass width and height to set viewport size (e.g. width=375, height=812 for mobile)',
        '  - The sessionId returned must be passed to ALL subsequent calls for this browser session',
        'Step 3: Call browser_screenshot to see what the page looks like.',
        '  - You will receive the actual rendered screenshot as an image — describe what you see',
        'Step 4: Interact with the page using browser_click, browser_type, browser_scroll.',
        'Step 5: Take more screenshots to verify the result of your interactions.',
        'Step 6: Use browser_get_dom to read HTML structure, browser_console_logs to check for JS errors.',
        '',
        '=== TOOL REFERENCE WITH ALL PARAMETERS ===',
        '',
        'browser_select_mode — Choose browser mode for the session',
        '  Params: mode (optional, "connect" or "headless") — set the session default',
        '  Call with no params to query available modes. Call with mode to set default.',
        '  Returns: connectAvailable, available options, currentMode, message',
        '',
        'browser_status — Check connection status',
        '  Params: none',
        '  Returns: connectAvailable (boolean), headlessSessions (list of active session IDs)',
        '',
        'browser_navigate — Open any URL in the browser',
        '  Params:',
        '    url (REQUIRED, string) — the URL to navigate to',
        '    width (optional, number) — viewport width in pixels (headless only, default 1024)',
        '    height (optional, number) — viewport height in pixels (headless only, default 768)',
        '    proxyServer (optional, string) — route a NEW session\'s traffic through this proxy, e.g. "127.0.0.1:8080".',
        '      Ignored if sessionId is set (proxy can only be chosen when the browser launches, not changed after).',
        '    sessionId (optional, string) — reuse an existing headless session',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: url (final URL after navigation), sessionId',
        '  IMPORTANT: Save the returned sessionId and pass it to all subsequent tool calls!',
        '  Viewport examples: desktop=1920x1080, laptop=1366x768, tablet=768x1024, mobile=375x812',
        '',
        'browser_screenshot — Capture what the page looks like right now',
        '  Params:',
        '    sessionId (optional, string) — the headless session to screenshot',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: PNG image as base64 (rendered as an image you can see and describe)',
        '',
        'browser_click — Click any element on the page (human-like by default)',
        '  Params:',
        '    selector (REQUIRED, string) — CSS selector of the element to click. Prefix "pierce/" to reach shadow DOM.',
        '    humanClick (optional, boolean, default true) — simulate full human mouse events',
        '      true: moves mouse to element center, fires mouseover→mouseenter→mousemove→mousedown→focus→mouseup→click',
        '      false: simple el.click() — faster but may not work with Select2/jQuery/custom dropdowns',
        '      Ignored (always simple click) when frameIndex is set — frames have no mouse of their own.',
        '    frameIndex (optional, number) — click inside a specific iframe by index (from browser_frames) instead',
        '      of the main page',
        '    sessionId (optional, string) — headless session ID',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: { success: true }',
        '  Selector examples: "#submit-btn", "button[type=submit]", ".nav-link", "a.login", ".select2-selection"',
        '  Works with: regular buttons, Select2 dropdowns, jQuery UI widgets, custom JS menus, any clickable element',
        '  After clicking, the tool automatically waits for the page to stabilize (DOM mutations settle)',
        '',
        'browser_type — Type text into any input field',
        '  Params:',
        '    selector (REQUIRED, string) — CSS selector of the input/textarea to type into. Prefix "pierce/" for shadow DOM.',
        '    text (REQUIRED, string) — the text to type',
        '    frameIndex (optional, number) — type inside a specific iframe by index (from browser_frames)',
        '    sessionId (optional, string) — headless session ID',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: { success: true }',
        '  Works with: text inputs, password fields, search bars, textareas, contenteditable elements',
        '',
        'browser_scroll — Scroll the page in any direction',
        '  Params:',
        '    x (optional, number, default 0) — horizontal scroll in pixels (positive=right, negative=left)',
        '    y (optional, number, default 0) — vertical scroll in pixels (positive=down, negative=up)',
        '    sessionId (optional, string) — headless session ID',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: { scrollX, scrollY } — final scroll position',
        '  Examples: scroll down 500px → y=500, scroll up → y=-500, scroll to bottom → y=99999',
        '',
        'browser_get_url — Get the current page URL',
        '  Params:',
        '    sessionId (optional, string) — headless session ID',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: { url } — the current page URL',
        '',
        'browser_get_dom — Get HTML (or plain text) source of the current page, optionally scoped',
        '  Params:',
        '    selector (optional, string) — scope to one subtree instead of the whole page. Prefix "pierce/" for shadow DOM.',
        '    format (optional, "html" or "text", default "html") — "text" strips tags, much smaller',
        '    maxLength (optional, number) — truncate to this many characters (default: unlimited)',
        '    frameIndex (optional, number) — read a specific iframe by index (from browser_frames)',
        '    sessionId (optional, string) — headless session ID',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: { dom } — or { dom, truncated: true, totalLength } if maxLength was hit',
        '  Useful for: finding CSS selectors, understanding page structure, checking element attributes',
        '  WARNING: a full unscoped HTML dump can be tens of thousands of characters. Prefer',
        '  browser_snapshot for exploring a page, or pass selector/format/maxLength to scope this down.',
        '',
        'browser_find — Search for element(s) by visible text and/or ARIA role, no CSS selector needed',
        '  Params:',
        '    text (optional, string) — substring, case-insensitive by default, matched against accessible name',
        '    role (optional, string) — filter by role, e.g. "button", "link", "textbox", "heading"',
        '    exact (optional, boolean, default false) — require an exact text match instead of substring',
        '    multiple (optional, boolean, default false) — return all matches instead of stopping at the first',
        '    maxResults (optional, number, default 10) — cap when multiple:true',
        '    sessionId, mode — standard params',
        '  At least one of text/role is required. Returns: { matches: [{ ref, role, name }] }',
        '  Each ref is a valid CSS selector: pass \'[data-mcp-ref="f1"]\' to browser_click/type/hover/select_option.',
        '  ("f" prefix keeps these refs distinct from browser_snapshot\'s "e" refs — the two never collide.)',
        '  PREFER THIS over browser_snapshot when you already know roughly what you\'re looking for by name/role —',
        '  it\'s a single targeted lookup instead of a full page dump.',
        '',
        'browser_get_element — Get full detail on ONE element by selector',
        '  Params:',
        '    selector (REQUIRED, string) — CSS selector. Prefix "pierce/" for shadow DOM.',
        '    styles (optional, string[]) — computed CSS properties to include (default: display, visibility, color,',
        '      background-color, font-size, font-weight). Pass your own list for anything else.',
        '    sessionId, mode — standard params',
        '  Returns: { tagName, attributes, boundingBox, visible, textContent, styles }',
        '  Use when you need to closely inspect ONE element — why it looks wrong, whether it\'s actually visible/enabled.',
        '',
        'browser_frames — List all iframes on the current page',
        '  Params: sessionId, mode — standard params',
        '  Returns: { frames: [{ index, url, name }] }',
        '  Pass an entry\'s index as frameIndex to browser_click/browser_type/browser_get_dom to target that iframe.',
        '  Shadow DOM does NOT need this tool — prefix any selector with "pierce/" instead (no frameIndex needed).',
        '',
        'browser_form_fill — Fill multiple form fields in one call',
        '  Params:',
        '    fields (REQUIRED, object) — map of CSS selector -> value, e.g. {"#email":"a@b.com","#country":"IN"}',
        '    submitSelector (optional, string) — CSS selector of a submit button to click after filling everything',
        '    sessionId, mode — standard params',
        '  Automatically picks the right interaction per element: types into text inputs/textareas, uses native',
        '  <select> selection for dropdowns, clicks checkboxes/radios (value "true"/"1" means check it).',
        '  Returns: { success: true, filled: [...selectors] }',
        '',
        'browser_auth — Set or clear HTTP Basic/Digest Auth credentials',
        '  Params:',
        '    username, password (required unless clear:true)',
        '    clear (optional, boolean) — remove previously set credentials',
        '    sessionId, mode — standard params',
        '  Call BEFORE browser_navigate to a password-protected URL (a native browser auth dialog, not a page form).',
        '',
        'browser_clipboard — Read or write the system clipboard from the page context',
        '  Params:',
        '    action (REQUIRED, "read" | "write")',
        '    text (required for "write") — text to write to the clipboard',
        '    sessionId, mode — standard params',
        '  Automatically grants clipboard permissions first — you do NOT need to call browser_emulate for this.',
        '  Use to verify a "Copy" button worked, or to paste text into a page that has no visible input for it.',
        '',
        'browser_profiles — List or delete named persistent browser profiles',
        '  Params:',
        '    action (REQUIRED, "list" | "delete")',
        '    name (required for "delete") — profile name',
        '  A profile\'s cookies/login state survive across separate MCP server runs (unlike a normal session, which is',
        '  wiped when it ends). Create one implicitly via browser_navigate\'s `profile` param on a brand-new session.',
        '',
        'browser_emulate — Emulate device/environment conditions on the current page',
        '  Params (pass only what you need, each applies independently):',
        '    device (optional, string) — known device name, e.g. "iPhone 15 Pro", "Pixel 7" (sets viewport+UA+touch)',
        '    colorScheme (optional, "light"|"dark"|"no-preference")',
        '    reducedMotion (optional, "reduce"|"no-preference")',
        '    timezone (optional, string) — IANA id, e.g. "America/New_York"',
        '    locale (optional, string) — sent as Accept-Language header (approximation)',
        '    geolocation (optional, {latitude, longitude}) — also grants the geolocation permission',
        '    permissions (optional, string[]) — e.g. ["clipboard-read","clipboard-write","notifications"]',
        '    networkThrottle (optional, "Slow 3G"|"Fast 3G"|"Slow 4G"|"Fast 4G"|"offline"|"none")',
        '    cpuThrottle (optional, number) — slowdown factor, e.g. 4 = 4x slower; pass 1 to clear',
        '    sessionId, mode — standard params',
        '  Returns: { success: true, applied: [...names of what was actually changed] }',
        '  Use cases: test responsive/mobile layouts, dark-mode UI, slow-network behavior, geolocation-gated features',
        '',
        'browser_snapshot — Get a compact accessibility-tree view (interactive/semantic elements only)',
        '  Params:',
        '    maxNodes (optional, number, default 300) — cap on elements included',
        '    diff (optional, boolean) — return only elements added/removed since your last snapshot',
        '      call in this session, instead of the full tree. Cheap way to check "did that click work?"',
        '    sessionId (optional, string) — headless session ID',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: { snapshot } — indented text list like: "- button \\"Submit\\" [ref=e12]"',
        '  PREFER THIS over browser_get_dom when exploring an unfamiliar page — it costs a tiny',
        '  fraction of the tokens a full HTML dump does. Each [ref=e12] is also a valid CSS selector:',
        '  pass \'[data-mcp-ref="e12"]\' directly as the selector for browser_click/type/hover/select_option.',
        '',
        'browser_stats — Cheap pre-check of page size before calling browser_get_dom',
        '  Params: sessionId, mode — standard params',
        '  Returns: { url, title, domNodeCount, approxHtmlLength, approxTextLength }',
        '  Call this on an unfamiliar page BEFORE browser_get_dom to decide whether a full dump is safe,',
        '  or whether to scope it (selector/maxLength) or use browser_snapshot/browser_extract instead.',
        '',
        'browser_execute — Run arbitrary JavaScript on the page',
        '  Params:',
        '    code (REQUIRED, string) — JavaScript to execute in the page context',
        '    sessionId (optional, string) — headless session ID',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: { result } — the return value of your code',
        '  Has full access to: window, document, jQuery ($), and all page globals',
        '  USE CASES:',
        '    Select2/jQuery dropdowns: jQuery("#select_project").val("8251").trigger("change")',
        '    Read values: document.querySelector("#total").textContent',
        '    Fill multiple fields at once: jQuery("#name").val("John"); jQuery("#email").val("a@b.com"); return "done"',
        '    Trigger form submit: document.querySelector("form").submit()',
        '    Check element exists: return !!document.querySelector(".success-message")',
        '    Complex widget interaction: any JavaScript the page supports',
        '  IMPORTANT: Use this when browser_click or browser_type cannot interact with custom widgets',
        '',
        'browser_console_logs — Read JavaScript console output',
        '  Params:',
        '    sessionId (optional, string) — headless session ID',
        '    mode (optional, "connect" or "headless") — override session default',
        '  Returns: { logs: [{ type, text, timestamp }] } — array of console messages',
        '  Log types: "log", "warn", "error", "info", "debug"',
        '  Useful for: debugging JS errors, checking API responses, finding runtime issues',
        '',
        'browser_page_errors — Read uncaught JavaScript exceptions (real crashes)',
        '  Params: sessionId, mode — standard params',
        '  Returns: { errors: [{ message, stack, timestamp }] }',
        '  DIFFERENT from browser_console_logs: that only catches explicit console.log/warn/error calls.',
        '  This catches a script that threw and stopped running, even if it never logged anything.',
        '  Check this whenever a page seems "stuck" or a feature silently does nothing.',
        '',
        'browser_keyboard — Press keyboard keys and key combinations',
        '  Params:',
        '    key (REQUIRED, string) — Key to press: "Enter", "Tab", "Escape", "ArrowDown", "ArrowUp", "Backspace", "Delete", "Space", "a", "1", etc.',
        '    modifiers (optional, array) — Modifier keys: ["Control"], ["Shift"], ["Alt"], ["Meta"], or combos like ["Control", "Shift"]',
        '    selector (optional, string) — Focus this element before pressing key',
        '    sessionId, mode — standard params',
        '  Use cases: submit form (Enter), next field (Tab), close modal (Escape), select all (Control+a), copy (Control+c), navigate menus (ArrowDown)',
        '',
        'browser_hover — Hover over an element to trigger menus/tooltips',
        '  Params:',
        '    selector (REQUIRED, string) — Element to hover over',
        '    sessionId, mode — standard params',
        '  Use cases: reveal dropdown menus, show tooltips, trigger hover effects',
        '',
        'browser_select_option — Select from native <select> dropdowns',
        '  Params:',
        '    selector (REQUIRED, string) — CSS selector of the <select> element',
        '    value (optional, string) — Option value to select',
        '    label (optional, string) — Visible text of option to select',
        '    sessionId, mode — standard params',
        '  Auto-triggers change events including jQuery. For Select2, use browser_execute instead.',
        '',
        'browser_wait_for — Wait for elements, text, or conditions',
        '  Params:',
        '    selector (optional, string) — Wait for this element to appear',
        '    text (optional, string) — Wait for this text to appear on page',
        '    textGone (optional, string) — Wait for this text to disappear',
        '    timeout (optional, number, default 10000) — Max wait in ms',
        '    visible (optional, boolean, default true) — Wait for visibility not just DOM presence',
        '    sessionId, mode — standard params',
        '  Use cases: wait for AJAX content, loading spinner to disappear, modal to open, success message',
        '',
        'browser_handle_dialog — Handle alert/confirm/prompt dialogs',
        '  Params:',
        '    action (REQUIRED, "accept" or "dismiss") — Accept or dismiss the dialog',
        '    promptText (optional, string) — Text to enter for prompt() dialogs',
        '    sessionId, mode — standard params',
        '  IMPORTANT: Call this BEFORE the action that triggers the dialog (e.g. before clicking delete button)',
        '',
        'browser_file_upload — Upload files to file inputs',
        '  Params:',
        '    selector (REQUIRED, string) — CSS selector of <input type="file">',
        '    paths (REQUIRED, string[]) — Array of absolute file paths to upload',
        '    sessionId, mode — standard params',
        '  Example: browser_file_upload({selector: "input[type=file]", paths: ["/home/user/doc.pdf"]})',
        '',
        'browser_drag_drop — Drag and drop elements',
        '  Params:',
        '    sourceSelector (REQUIRED, string) — Element to drag',
        '    targetSelector (REQUIRED, string) — Element to drop onto',
        '    sessionId, mode — standard params',
        '  Use cases: kanban boards, sortable lists, reordering items, file drop zones',
        '',
        'browser_tabs — Manage browser tabs',
        '  Params:',
        '    action (REQUIRED, "list" | "new" | "switch" | "close" | "screenshot") — Tab action',
        '    url (optional, string) — URL for new tab',
        '    index (optional, number) — Tab index for switch/close/screenshot (0-based)',
        '    sessionId, mode — standard params',
        '  Use cases: OAuth popups, multi-page workflows, open links in new tabs',
        '  "screenshot" captures a specific tab by index WITHOUT switching the active tab — use it to',
        '  compare two open tabs, or peek at a background tab, without disrupting the current one.',
        '',
        'browser_navigate_back — Go back to previous page',
        '  Params: sessionId, mode — standard params',
        '  Equivalent to clicking the browser back button',
        '',
        'browser_navigate_forward — Go forward to the next page (after a back navigation)',
        '  Params: sessionId, mode — standard params',
        '  Equivalent to clicking the browser forward button. If there is no forward history, the page just stays put.',
        '',
        'browser_reload — Reload the current page',
        '  Params:',
        '    ignoreCache (optional, boolean, default false) — hard refresh bypassing the cache (like Ctrl+Shift+R)',
        '    sessionId, mode — standard params',
        '  Returns: { success: true, url }',
        '',
        'browser_cookies — Get, set, delete, or clear cookies on the current page',
        '  Params:',
        '    action (REQUIRED, "get" | "set" | "delete" | "clear")',
        '    name, value, domain, path, httpOnly, secure, expires — for "set"/"delete"',
        '    sessionId, mode — standard params',
        '  Use cases: inspect auth/session cookies, inject a saved session to skip login, clean cookies between test runs',
        '',
        'browser_storage — Get, set, or clear localStorage/sessionStorage on the current page',
        '  Params:',
        '    action (REQUIRED, "get" | "set" | "clear")',
        '    area ("localStorage" | "sessionStorage"), key, value — for "set"',
        '    sessionId, mode — standard params',
        '  Combine with browser_cookies to save/restore full session state across calls',
        '',
        'browser_extract — Extract structured text/attributes without dumping raw HTML',
        '  Params:',
        '    selector (optional) — scope extraction; omit to get the whole page\'s visible text',
        '    attribute (optional) — extract this attribute (e.g. "href") instead of text',
        '    multiple (optional, boolean) — return an array for every match, not just the first',
        '    sessionId, mode — standard params',
        '  PREFER THIS over browser_get_dom when you just need content, not markup',
        '',
        'browser_pdf — Render the current page to a PDF file on disk',
        '  Params:',
        '    path (REQUIRED, string) — absolute file path to save to',
        '    format (optional, "A4"|"Letter"|"Legal"|"Tabloid"|"A3"|"A5", default "A4")',
        '    landscape (optional, boolean, default false)',
        '    sessionId, mode — standard params',
        '  Returns: { success, path, sizeBytes } — the PDF itself is saved to disk, not returned inline',
        '',
        'browser_network — Inspect or control network traffic (headless mode only for blocking)',
        '  Params:',
        '    action (REQUIRED, "list" | "clear" | "block" | "unblock")',
        '    resourceTypes (for "block", e.g. ["image","font","stylesheet","media"])',
        '    limit (for "list", default 100)',
        '    sessionId, mode — standard params',
        '  Use cases: debug failed requests, check response statuses, block images/fonts to speed up a page',
        '  NOTE: blocking is unavailable in connect mode (would intercept the user\'s live browsing)',
        '',
        'browser_downloads — Configure a download directory and list what has landed there',
        '  Params:',
        '    action (REQUIRED, "configure" | "list")',
        '    path (REQUIRED for "configure") — absolute directory to save downloads to',
        '    sessionId, mode — standard params',
        '  Call "configure" BEFORE triggering a download (e.g. clicking a download link), then "list" after',
        '',
        'browser_macro — Save a named sequence of tool calls, replay it by name later',
        '  Params:',
        '    action (REQUIRED, "save" | "run" | "list" | "delete")',
        '    name (required for save/run/delete) — macro name',
        '    steps (required for "save") — array of { tool, args } to run in order',
        '    sessionId, mode (for "run") — merged into every step\'s args, so one macro can target any session',
        '  Example: save({name:"login", steps:[{tool:"browser_click",args:{selector:"#user"}}, ...]}) once,',
        '  then run({name:"login", sessionId}) any time — collapses a repeated flow into one tool call.',
        '',
        '=== COMMON USE CASES ===',
        '',
        'CHECK A WEBSITE:',
        '  browser_navigate({url: "https://example.com"}) → browser_screenshot()',
        '',
        'CHECK MOBILE LAYOUT:',
        '  browser_navigate({url: "https://example.com", width: 375, height: 812}) → browser_screenshot()',
        '',
        'FILL AND SUBMIT A FORM:',
        '  browser_navigate({url: "https://example.com/contact"})',
        '  browser_type({selector: "input[name=email]", text: "user@example.com"})',
        '  browser_type({selector: "textarea[name=message]", text: "Hello!"})',
        '  browser_click({selector: "button[type=submit]"})',
        '  browser_screenshot()  // verify form was submitted',
        '',
        'LOGIN TO A SITE:',
        '  browser_navigate({url: "https://example.com/login"})',
        '  browser_type({selector: "#username", text: "myuser"})',
        '  browser_type({selector: "#password", text: "mypass"})',
        '  browser_click({selector: "#login-btn"})',
        '  browser_screenshot()  // verify logged in',
        '',
        'DEBUG A JS ERROR:',
        '  browser_navigate({url: "https://example.com"}) → browser_console_logs()',
        '',
        'INSPECT PAGE STRUCTURE:',
        '  browser_navigate({url: "https://example.com"}) → browser_get_dom()',
        '',
        'MULTI-STEP FLOW:',
        '  browser_navigate({url: "https://shop.example.com"})',
        '  browser_click({selector: ".product-card:first-child .add-to-cart"})',
        '  browser_click({selector: ".cart-icon"})',
        '  browser_screenshot()  // verify cart',
        '  browser_click({selector: "#checkout-btn"})',
        '  browser_type({selector: "#email", text: "buyer@example.com"})',
        '  browser_click({selector: "#place-order"})',
        '  browser_screenshot()  // verify order confirmation',
        '',
        'SELECT2/JQUERY DROPDOWN (use browser_execute for custom widgets):',
        '  browser_execute({code: \'jQuery("#select_project").val("8251").trigger("change")\'})',
        '  browser_execute({code: \'jQuery("#select_task").val("General").trigger("change")\'})',
        '  browser_screenshot()  // verify selections',
        '',
        'CLICK SELECT2 DROPDOWN (human-like click opens the dropdown):',
        '  browser_click({selector: ".select2-selection"})  // opens dropdown with human mouse events',
        '  browser_click({selector: ".select2-results__option:nth-child(3)"})  // select an option',
        '',
        'SCROLL AND CAPTURE LONG PAGE:',
        '  browser_navigate({url: "https://example.com"}) → browser_screenshot()',
        '  browser_scroll({y: 800}) → browser_screenshot()  // see below the fold',
        '  browser_scroll({y: 800}) → browser_screenshot()  // see even further down',
        '',
        'SUBMIT FORM WITH ENTER KEY:',
        '  browser_type({selector: "#search", text: "query"})',
        '  browser_keyboard({key: "Enter"})  // press Enter to submit',
        '',
        'NAVIGATE DROPDOWN WITH KEYBOARD:',
        '  browser_click({selector: "#dropdown-trigger"})',
        '  browser_keyboard({key: "ArrowDown"})  // move to first option',
        '  browser_keyboard({key: "ArrowDown"})  // move to second option',
        '  browser_keyboard({key: "Enter"})  // select it',
        '',
        'HOVER MENU → CLICK ITEM:',
        '  browser_hover({selector: ".main-nav > li:nth-child(2)"})',
        '  browser_click({selector: ".submenu a.settings"})',
        '',
        'SELECT FROM NATIVE DROPDOWN:',
        '  browser_select_option({selector: "#country", label: "United States"})',
        '  browser_select_option({selector: "#state", value: "CA"})',
        '',
        'WAIT FOR AJAX THEN VERIFY:',
        '  browser_click({selector: "#save-btn"})',
        '  browser_wait_for({text: "Saved successfully", timeout: 5000})',
        '  browser_screenshot()  // confirm success message',
        '',
        'HANDLE CONFIRM DIALOG BEFORE DELETE:',
        '  browser_handle_dialog({action: "accept"})  // arm the handler first',
        '  browser_click({selector: "#delete-btn"})  // this triggers confirm()',
        '',
        'UPLOAD FILE:',
        '  browser_file_upload({selector: "input[type=file]", paths: ["/home/user/report.pdf"]})',
        '  browser_click({selector: "#upload-btn"})',
        '',
        'DRAG AND DROP (KANBAN):',
        '  browser_drag_drop({sourceSelector: ".task-card:first-child", targetSelector: ".column-done"})',
        '',
        'OAUTH FLOW WITH TABS:',
        '  browser_click({selector: "#login-with-google"})  // opens popup',
        '  browser_tabs({action: "list"})  // see all tabs',
        '  browser_tabs({action: "switch", index: 1})  // switch to popup',
        '  browser_type({selector: "#email", text: "user@gmail.com"})',
        '  browser_keyboard({key: "Enter"})',
        '',
        '=== SESSION MANAGEMENT ===',
        'When you call browser_navigate in headless mode, it returns a sessionId (e.g. "session-a1b2c3d4").',
        'You MUST pass this sessionId to all subsequent tool calls to use the same browser.',
        'The session persists: cookies, login state, navigation history are all maintained.',
        'Multiple sessions can exist simultaneously — each is an independent browser.',
        '',
        '=== IMPORTANT REMINDERS ===',
        '- You are NOT limited to fetching data. You have a REAL browser that renders pages.',
        '- Always use browser_navigate FIRST to open a page before using other tools.',
        '- Always pass the sessionId from browser_navigate to subsequent calls.',
        '- Take screenshots frequently to verify what happened after interactions.',
        '- Use browser_get_dom to find CSS selectors when you don\'t know them.',
        '- Check browser_console_logs when something seems broken on a page.',
        '- You can open any URL: public sites, localhost:3000, 127.0.0.1:8080, any web app.',
        '- The browser handles JavaScript, CSS, AJAX — pages render exactly like a real browser.',
      ].join('\n')
    }
  );

  for (const tool of tools) {
    server.registerTool(tool.name, tool.options, tool.handler);
    registerTool(tool);
  }

  const transport = new StdioServerTransport();
  await server.connect(transport);

  logger.info('browser-control MCP server started', { tools: tools.map(t => t.name) });
}

main().catch((error: unknown) => {
  process.stderr.write(JSON.stringify({
    level: 'error',
    message: 'Fatal startup error',
    error: String(error)
  }) + '\n');
  process.exit(1);
});
